// Automatically generated by scripts/generate-releases.mjs
export type PlatformId = 'windows' | 'macos' | 'linux';

export interface ReleaseArtifact {
  id: string;
  name: string;
  platformId: PlatformId;
  platformLabel: string;
  architecture: string;
  architectureLabel: string;
  artifactType: string;
  extension: string;
  downloadUrl: string;
  sizeBytes: number;
  sizeFormatted: string;
  checksum: string;
}

export interface ReleasePlatform {
  id: PlatformId;
  label: string;
  icon: 'Monitor' | 'Apple' | 'Terminal';
  artifacts: ReleaseArtifact[];
}

export interface Release {
  version: string;
  status: 'stable' | 'pre-release';
  releasedAt: string;
  releasedDateFormatted: string;
  summary: string;
  notes: string;
  platforms: ReleasePlatform[];
}

export const GENERATED_RELEASES: Release[] = [
  {
    "version": "v1.2.0-beta",
    "status": "pre-release",
    "releasedAt": "2026-09-16T13:01:16Z",
    "releasedDateFormatted": "September 16, 2026",
    "summary": "HUNTARA desktop preview release (v1.2.0-beta) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.2.0-beta-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.2.0-beta/LeadForge.OS-1.2.0-beta-win-x64.exe",
            "sizeBytes": 100336820,
            "sizeFormatted": "95.7 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.5",
    "status": "pre-release",
    "releasedAt": "2026-09-06T16:11:35Z",
    "releasedDateFormatted": "September 6, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.5) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.5-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.5/LeadForge.OS-1.1.1-beta.5-win-x64.exe",
            "sizeBytes": 100312108,
            "sizeFormatted": "95.7 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.4.2",
    "status": "pre-release",
    "releasedAt": "2026-09-02T18:36:18Z",
    "releasedDateFormatted": "September 3, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.4.2) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.4.2-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.4.2/LeadForge.OS-1.1.1-beta.4.2-win-x64.exe",
            "sizeBytes": 99874466,
            "sizeFormatted": "95.2 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.4.1",
    "status": "pre-release",
    "releasedAt": "2026-09-02T15:13:34Z",
    "releasedDateFormatted": "September 2, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.4.1) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.4.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.4.1/LeadForge.OS-1.1.1-beta.4.1-win-x64.exe",
            "sizeBytes": 99870937,
            "sizeFormatted": "95.2 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.3",
    "status": "pre-release",
    "releasedAt": "2026-09-02T12:23:56Z",
    "releasedDateFormatted": "September 2, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.3) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.3-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.3/LeadForge.OS-1.1.1-beta.3-win-x64.exe",
            "sizeBytes": 99871395,
            "sizeFormatted": "95.2 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.2",
    "status": "pre-release",
    "releasedAt": "2026-08-26T21:13:38Z",
    "releasedDateFormatted": "August 27, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.2) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.2-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.2/LeadForge.OS-1.1.1-beta.2-win-x64.exe",
            "sizeBytes": 99907618,
            "sizeFormatted": "95.3 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.1.1-beta.1",
    "status": "pre-release",
    "releasedAt": "2026-08-25T15:31:56Z",
    "releasedDateFormatted": "August 25, 2026",
    "summary": "HUNTARA desktop preview release (v1.1.1-beta.1) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.1.1-beta.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.1.1-beta.1/LeadForge.OS-1.1.1-beta.1-win-x64.exe",
            "sizeBytes": 99874639,
            "sizeFormatted": "95.2 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.0.0-beta.6",
    "status": "pre-release",
    "releasedAt": "2026-08-25T14:49:24Z",
    "releasedDateFormatted": "August 25, 2026",
    "summary": "HUNTARA desktop preview release (v1.0.0-beta.6) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.0.0-beta.6-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.0.0-beta.6/LeadForge.OS-1.0.0-beta.6-win-x64.exe",
            "sizeBytes": 99874712,
            "sizeFormatted": "95.2 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.0.0-beta.5",
    "status": "pre-release",
    "releasedAt": "2026-08-05T19:04:53Z",
    "releasedDateFormatted": "August 6, 2026",
    "summary": "HUNTARA desktop preview release (v1.0.0-beta.5) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.0.0-beta.5-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.0.0-beta.5/LeadForge.OS-1.0.0-beta.5-win-x64.exe",
            "sizeBytes": 99547638,
            "sizeFormatted": "94.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.0.0-beta.4",
    "status": "pre-release",
    "releasedAt": "2026-08-05T18:16:47Z",
    "releasedDateFormatted": "August 5, 2026",
    "summary": "HUNTARA desktop preview release (v1.0.0-beta.4) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.0.0-beta.4-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.0.0-beta.4/LeadForge.OS-1.0.0-beta.4-win-x64.exe",
            "sizeBytes": 99546828,
            "sizeFormatted": "94.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.0.0-beta.3",
    "status": "pre-release",
    "releasedAt": "2026-08-05T17:44:10Z",
    "releasedDateFormatted": "August 5, 2026",
    "summary": "HUNTARA desktop preview release (v1.0.0-beta.3) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-1.0.0-beta.3-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.0.0-beta.3/LeadForge.OS-1.0.0-beta.3-win-x64.exe",
            "sizeBytes": 99546859,
            "sizeFormatted": "94.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v1.0.0-beta.1",
    "status": "pre-release",
    "releasedAt": "2026-08-01T14:33:36Z",
    "releasedDateFormatted": "August 1, 2026",
    "summary": "HUNTARA desktop preview release (v1.0.0-beta.1) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-0.1.2-beta.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v1.0.0-beta.1/LeadForge.OS-0.1.2-beta.1-win-x64.exe",
            "sizeBytes": 99520493,
            "sizeFormatted": "94.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v0.1.2-beta.1",
    "status": "pre-release",
    "releasedAt": "2026-08-01T14:03:16Z",
    "releasedDateFormatted": "August 1, 2026",
    "summary": "HUNTARA desktop preview release (v0.1.2-beta.1) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-0.1.1-beta.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v0.1.2-beta.1/LeadForge.OS-0.1.1-beta.1-win-x64.exe",
            "sizeBytes": 98456697,
            "sizeFormatted": "93.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v0.1.1-beta.1",
    "status": "pre-release",
    "releasedAt": "2026-08-01T09:35:57Z",
    "releasedDateFormatted": "August 1, 2026",
    "summary": "HUNTARA desktop preview release (v0.1.1-beta.1) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v0.1.1-beta.1/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
            "sizeBytes": 98454876,
            "sizeFormatted": "93.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  },
  {
    "version": "v0.1.0-beta.2",
    "status": "pre-release",
    "releasedAt": "2026-08-01T09:28:57Z",
    "releasedDateFormatted": "August 1, 2026",
    "summary": "HUNTARA desktop preview release (v0.1.0-beta.2) running locally on your hardware.",
    "notes": "Maintenance release with reliability and stability enhancements.",
    "platforms": [
      {
        "id": "windows",
        "label": "Windows",
        "icon": "Monitor",
        "artifacts": [
          {
            "id": "windows-x64-exe",
            "name": "LeadForge.OS-0.1.0-beta.1-win-x64.exe",
            "platformId": "windows",
            "platformLabel": "Windows",
            "architecture": "x64",
            "architectureLabel": "x64",
            "artifactType": "NSIS Installer",
            "extension": "exe",
            "downloadUrl": "https://github.com/kjxcodez/huntara/releases/download/v0.1.0-beta.2/LeadForge.OS-0.1.0-beta.1-win-x64.exe",
            "sizeBytes": 98454858,
            "sizeFormatted": "93.9 MB",
            "checksum": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
          }
        ]
      }
    ]
  }
];

export function getAllReleases(): Release[] {
  return GENERATED_RELEASES;
}

export function normalizeVersion(v: string): string {
  if (!v) return '';
  return v.trim().toLowerCase();
}

export function getReleaseByVersion(version: string): Release | undefined {
  const norm = normalizeVersion(version);
  return GENERATED_RELEASES.find(r => {
    const rNorm = normalizeVersion(r.version);
    return rNorm === norm || rNorm === `v${norm}` || `v${rNorm}` === norm;
  });
}

export function normalizePlatformId(p: string): PlatformId | null {
  if (!p) return null;
  const lower = p.trim().toLowerCase();
  if (lower === 'windows' || lower === 'win') return 'windows';
  if (lower === 'macos' || lower === 'mac' || lower === 'darwin') return 'macos';
  if (lower === 'linux') return 'linux';
  return null;
}

export function getReleasePlatform(
  version: string,
  platformInput: string
): { release: Release; platform: ReleasePlatform } | null {
  const release = getReleaseByVersion(version);
  if (!release) return null;
  const platformId = normalizePlatformId(platformInput);
  if (!platformId) return null;
  const platform = release.platforms.find(p => p.id === platformId);
  if (!platform) return null;
  return { release, platform };
}

export function getLatestRelease(): Release {
  return GENERATED_RELEASES.find(r => r.status === 'stable') || GENERATED_RELEASES[0];
}
